#!/bin/sh

case "$1" in
	start)
		mv /var/log/cv.log /var/log/cvlogs/`date +%s`.log
		find /var/log/cvlogs +atime 4 | rm -f -
    cd /home/pi/pulse-cv
		./cv.out > /var/log/cv.log &
		;;
	stop)
		killall cv.out
		;;
	*)
		echo "usage start|stop"
		;;
esac
